export default {
    login: 'remoo1901',
    id: 42133389,
    node_id: 'MDQ6VXNlcjQyMTMzMzg5',
    avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/remoo1901',
    html_url: 'https://github.com/remoo1901',
    followers_url: 'https://api.github.com/users/remoo1901/followers',
    following_url:
      'https://api.github.com/users/remoo1901/following{/other_user}',
    gists_url: 'https://api.github.com/users/remoo1901/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/remoo1901/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/remoo1901/subscriptions',
    organizations_url: 'https://api.github.com/users/remoo1901/orgs',
    repos_url: 'https://api.github.com/users/remoo1901/repos',
    events_url: 'https://api.github.com/users/remoo1901/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/remoo1901/received_events',
    type: 'User',
    site_admin: false,
    name: 'Remon Abdou',
    company: 'Coding Addict',
    blog: 'www.remonabdou.com',
    location: 'New Jersey',
    email: null,
    hireable: null,
    twitter_username: 'remon mansy',
    public_repos: 152,
    public_gists: 0,
    followers: 1495,
    following: 0,
    created_at: '2018-08-06T06:48:23Z',
    updated_at: '2020-07-08T05:01:32Z',
  };